### ISSUE TITLE
your code is working for me

### ISSUE THREAD

**Issue by ozkanpakdil** [tigerinus/quakus-graphql-demo#1]
I ran the quarkus with gradle command
![image](https://user-images.githubusercontent.com/604405/174406293-869b7bd4-1f79-47aa-90e4-24f41ba41a3f.png)
and I ran nodejs tester like below
![image](https://user-images.githubusercontent.com/604405/174406365-7cd115d2-b78d-4df7-9e10-b140a04fdc0a.png)

only problem I needed to manually npm install graphql, anyway after I call createPerson from firefox I saw the created in the console. so this code is working

**Comment by tigerinus** [comment]
@ozkanpakdil I'm glad this works for you. 👍🏻 

Was there any issue?

**Comment by ozkanpakdil** [comment]
only npm install did not install graphql, do you get any error ?

**Comment by tigerinus** [comment]
> only npm install did not install graphql, do you get any error ?
That's weird. I see `graphql` installed along with `graphql-ws`:

![image](https://user-images.githubusercontent.com/7172560/174504738-dc4e1d02-0abc-48d7-b53d-dffafa690fdb.png)
